=== firewire80a/Mexico/mexico.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="pais">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="poblacion" type="xs:integer"/>
                <xs:element name="continente" type="xs:string"/>
                <xs:element name="capital">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="coordenadas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="latitud" type="xs:decimal"/>
                                        <xs:element name="longitud" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="fotografias">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="foto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string"/>
                                        <xs:element name="url" type="xs:anyURI"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== firewire80a/Mexico/mexico.xml
<?xml version="1.0" encoding="UTF-8"?>
<pais xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mexico.xsd">
    <nombre>mexico</nombre>
    <poblacion>126014024</poblacion>
    <continente>america</continente>
    <capital>
        <nombre>ciudad de mexico</nombre>
        <coordenadas>
            <latitud>19.432608</latitud>
            <longitud>-99.133209</longitud>
        </coordenadas>
    </capital>
    <fotografias>
        <foto>
            <nombre>chichen itza</nombre>
            <descripcion>ruinas arqueologicas mayas en yucatan</descripcion>
            <url>https://cdn.britannica.com/86/179586-138-8B763D72/Overview-Chichen-Itza-Yucatan-Mexico.jpg</url>
        </foto>
        <foto>
            <nombre>playa del carmen</nombre>
            <descripcion>hermosa playa en la riviera maya</descripcion>
            <url>https://viajeronomada.com/wp-content/uploads/2016/01/cancunoplayadelcarmen.jpg</url>
        </foto>
    </fotografias>
</pais>
